simulation_metadata:
  num_episodes: 2
  num_steps_per_episode: 5
  num_substeps_per_step: 1
  calibration: false
  device: 'cpu'

  max_x: 10
  max_y: 10
  max_speed: 0.5
  min_speed: -0.5
  max_force: 3.0
  
  num_birds: 40
  num_rewards: 5

  neighbor_radius: 4.0
  separation_distance: 1.0

  locations_file: 'data/10x40/birds-coords.csv'
  reward_vector_file: 'data/10x40/reward-coords.csv'

  cohesion_weight: 1.0
  alignment_weight: 0.1
  cognitive_weight: 0.7

state:
  environment:
    bounds:
      name: "Grid Bounds"
      learnable: false
      shape: 2
      dtype: 'int'
      initialization_function: null
      value:
        - ${simulation_metadata.max_x}
        - ${simulation_metadata.max_y}
    
    radius:
      name: "Radius"
      learnable: false
      shape: 
        - 1
      dtype: 'int'
      initialization_function: null
      value: ${simulation_metadata.neighbor_radius}

    separation_distance:
      name: "Separation Distance for Boids"
      learnable: false
      shape: 
        - 1
      dtype: 'int'
      initialization_function: null
      value: ${simulation_metadata.separation_distance}
    
    state_value:
      name: "Value of State based on Successor Representation"
      learnable: false
      shape:
        - ${simulation_metadata.max_x}
        - ${simulation_metadata.max_y}
      dtype: 'float'
      initialization_function:
        generator: 'compute_sr_values'
        arguments:
          gamma:
            name: "Memory decay parameter"
            learnable: false
            shape:
              - 1
            value: 0.9
            initialization_function: null
          reward_vector:
            name: "Reward Distribution in the Environment"
            learnable: false
            shape: null
            initialization_function: null
            value: ${simulation_metadata.reward_vector_file}
  
  agents:
    bird:
      number: ${simulation_metadata.num_birds}
      properties:
        location:
          name: "Spatial position of agent"
          learnable: false
          shape:
            - ${state.agents.bird.number}
            - 2
          dtype: 'float'
          initialization_function:
            generator: 'read_from_file'
            arguments:
              file_path:
                name: "Initial locations file"
                learnable: false
                shape: null
                value: ${simulation_metadata.locations_file}
                initialization_function: null
      
        velocity:
          name: "Velocity of the agent"
          learnable: false
          shape:
            - ${state.agents.bird.number}
            - 2
          dtype: 'float'
          initialization_function:
            generator: 'random_float'
            arguments:
              lower_limit:
                name: 'Lower Bound'
                learnable: false
                shape:
                  - 1
                value: ${simulation_metadata.min_speed}
                initialization_function: null
              upper_limit:
                name: 'Upper Bound'
                learnable: false
                shape:
                  - 1
                value: ${simulation_metadata.max_speed}
                initialization_function: null

  network:
    agent_agent:
      follower_birds:
        type: 'map'
        arguments: null
  
  objects:
    food:
      number: ${simulation_metadata.num_rewards}
      properties:
        location:
          name: "Reward for State Location"
          learnable: false
          shape:
            - ${simulation_metadata.num_rewards}
            - 2
          dtype: 'float'
          initialization_function:
            generator: 'read_from_file'
            arguments:
              file_path:
                name: "Reward locations file"
                learnable: false
                shape: null
                value: ${simulation_metadata.reward_vector_file}
                initialization_function: null
        
        nutritional_value:
          name: "Amount of food remaining at location"
          learnable: false
          shape:
            - ${simulation_metadata.max_x}
            - ${simulation_metadata.max_y}
          dtype: 'float'
          value: 1.0
          initialization_function: null

substeps:
  '0':
    name: "Move"
    description: 'Birds move based on boids steering algorithm'
    active_agents:
      - 'bird'
    observation:
      bird:
        observe_neighbors:
          generator: 'ObserveNeighbors'
          arguments: null
          input_variables:
            location: 'agents/bird/location'
            neighbor_radius: 'environment/radius'
          output_variables:
            - neighbor_mask
  
    policy:
      bird:
        social_steering:
          generator: "SocialSteering"
          arguments:
            cohesion_weight:
              name: 'Cohesion Weight'
              learnable: false
              shape:
                - 1
              value: ${simulation_metadata.cohesion_weight}
              initialization_function: null
            alignment_weight:
              name: 'Alignment Weight'
              learnable: false
              shape:
                - 1
              value: ${simulation_metadata.alignment_weight}
              initialization_function: null
          input_variables:
            location: 'agents/bird/location'
            velocity: 'agents/bird/velocity'
            separation_distance: 'environment/separation_distance'
          output_variables:
            - social_steering
        
        memory_steering:
          generator: "MemorySteering"
          arguments: null
          input_variables:
            location: 'agents/bird/location'
            velocity: 'agents/bird/velocity'
            state_value: 'environment/state_value'
          output_variables:
            - memory_steering
    
    transition:
      update_location_velocity:
        generator: "UpdateLocationVelocity"
        arguments:
          cognitive_weight:
            name: "Cognitive abilities of the agent"
            learnable: false
            shape:
              - 1
            value: ${simulation_metadata.cognitive_weight}
            initialization_function: null
        input_variables:
          location: 'agents/bird/location'
          velocity: 'agents/bird/velocity'
        output_variables:
          - location
          - velocity
  
  # '1':
  #   name: "Eat"
  #   description: "Birds stop to eat food based on MVT"
  #   active_agents:
  #     - 'bird'
  #   observation: null
  #   policy:
  #     bird:
  #       decide_eat_or_move:
  #         generator: "DecideEatOrMove"
  #         arguments: null
  #         input_variables:
  #           location: 'agents/bird/location'
  #           food_coordinates: 'objects/food/location'
  #           nutritional_value: 'objects/food/nutritional_value'
  #         output_variables:
  #           - eating_decision
        
  #   transition:
  #     update_food_and_location:
  #       generator: "UpdateFoodAndLocation"
  #       arguments: null
  #       input_variables:
  #           location: 'agents/bird/location'
  #           food_coordinates: 'objects/food/location'
  #           nutritional_value: 'objects/food/nutritional_value'
  #           bounds: 'environment/bounds'
  #       output_variables:
  #         - location
  #         - nutritional_value